# Makefile (php)
#
# Created: 2020.04.20
# Author: Michael Spencer
# License: MIT


APP = helloworld.php
RUN = php -f

.SUFFIXES: .php
.PHONY: all run clean distclean
#.SILENT: run

all: # no-op

run:
	$(RUN) $(APP)

clean: # no-op

distclean: # no-op

